site_name: abarorm
site_description: >
  abarorm is a lightweight and easy-to-use Object-Relational Mapping (ORM)
  library for SQLite databases in Python. It provides a simple and intuitive
  interface for managing database models and interactions.
site_url: https://prodbygodfather.github.io/abarorm/

repo_url: https://github.com/prodbygodfather/abarorm
repo_name: abarorm
edit_uri: edit/main/docs/

# =========================
# Navigation
# =========================
nav:
  - Home:
      - en: index.md
      - fa: index.fa.md
  - Introduction:
      - en: Introduction.md
      - fa: Introduction.fa.md
  - Basic Usage:
      - en: basic_usage.md
      - fa: basic_usage.fa.md
  - Modeling:
      - en:
          - SQLite Modeling: modeling/sqlite_modeling.md
          - PostgreSQL Modeling: modeling/postgresql_modeling.md
      - fa:
          - مدل‌سازی SQLite: modeling/sqlite_modeling.fa.md
          - مدل‌سازی PostgreSQL: modeling/postgresql_modeling.fa.md
  - Field Types:
      - en: field_types.md
      - fa: field_types.fa.md
  - API Reference:
      - en: api_reference.md
      - fa: api_reference.fa.md
  - Issues:
      - en: issues.md
      - fa: issues.fa.md

# =========================
# Theme (Material)
# =========================
theme:
  name: material
  language: en

  icon:
    repo: fontawesome/brands/github

  logo: images/logo.png
  favicon: images/favicon.ico

  font:
    text: Roboto
    code: Roboto Mono

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: yellow
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: yellow
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.toggle
    - navigation.top
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - search.highlight
    - mermaid

# =========================
# Markdown Extensions
# =========================
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true

  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

# =========================
# Plugins
# =========================
plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en: English
        fa: فارسی
      no_translation:
        en: "This page isn't translated to English."
        fa: "این صفحه به فارسی ترجمه نشده است."
      translate_nav:
        en:
          Home: Home
          Introduction: Introduction
          Basic Usage: Basic Usage
          Modeling: Modeling
          Field Types: Field Types
          API Reference: API Reference
          Issues: Issues
        fa:
          Home: خانه
          Introduction: مقدمه
          Basic Usage: استفاده پایه
          Modeling: مدل‌سازی
          Field Types: نوع فیلد
          API Reference: مراجع API
          Issues: مسائل

# =========================
# Extra
# =========================
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/prodbygodfather/abarorm
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/prodbygodfathers

  alternate:
    - name: English
      link: /en/
      lang: en
    - name: فارسی
      link: /fa/
      lang: fa

# =========================
# Footer
# =========================
copyright: >
  Copyright © 2024 AbarVision Co —
  Mahdi Ghasemi (Dokey)


extra_css:
  - stylesheets/extra.css
